[versions]
agp = "9.4.0"
android-compileSdk = "37"
android-minSdk = "24"
android-targetSdk = "37"
androidx-core = "1.18.0"
androidx-activityCompose = "1.13.0"
androidx-lifecycle = "2.11.0"
coil3 = "3.6.0"
compose-kuiver = "0.4.1"
compose-material-icon = "1.7.3"
compose-material3 = "1.12.0-alpha03"
compose-multiplatform = "1.12.0"
compose-webview = "2.0.3"
cryptohash = "1.0.2"
desugar_jdk_libs = "2.1.5"
espressoCore = "3.7.0"
file-kit = "0.15.0"
junit = "4.13.2"
junit-android = "1.3.0"
kmp-zip = "0.15.0"
kotlin = "2.4.10"
kotlin-atomicfu = "0.33.0"
kotlin-compose-compiler = "2.4.10"
kotlin-datetime = "0.8.0"
kotlin-immutable = "0.5.2"
kotlin-serialization = "1.11.0"
kotlinx-coroutines = "1.11.0"
ksoup = "0.2.6"
ktor = "3.5.2"
mediamp = "0.3.2"
zoomimage = "1.7.0-alpha01"
dataStore = "1.2.1"

[libraries]
gradle-plugin-agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle-plugin-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-multiplatform" }
gradle-plugin-compose-compiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin-compose-compiler" }
gradle-plugin-serialization = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }

kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlin-atomicfu" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime" }
kotlinx-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutable" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlinx-serialization-proto = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlin-serialization" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-android" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-kuiver = { module = "io.github.justdeko:kuiver", version.ref = "compose-kuiver" }
compose-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-material-icon" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
compose-mediamp-all = { module = "org.openani.mediamp:mediamp-all", version.ref = "mediamp" }
compose-mediamp-runtime = { module = "org.openani.mediamp:mediamp-mpv-runtime", version.ref = "mediamp" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-ui-graphics = { module = "org.jetbrains.compose.ui:ui-graphics", version.ref = "compose-multiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-webview = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "compose-webview" }

coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil3-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
cryptohash = { module = "com.appmattus.crypto:cryptohash", version.ref = "cryptohash" }
filekit-coil = { module = "io.github.vinceglb:filekit-coil", version.ref = "file-kit" }
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "file-kit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "file-kit" }
kmp-zip = { module = "no.synth:kmp-zip", version.ref = "kmp-zip" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
zoomimage-coil3 = { module = "io.github.panpf.zoomimage:zoomimage-compose-coil3", version.ref = "zoomimage" }

# DataStore
androidx-datastore-core-okio = { group = "androidx.datastore", name = "datastore-core-okio", version.ref = "dataStore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }
androidx-datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "dataStore" }

[bundles]
datastore = [
    "androidx-datastore-core-okio",
    "androidx-datastore-preferences",
    "androidx-datastore-preferences-core",
]
file-kit = [
    "filekit-coil",
    "filekit-core",
    "filekit-dialogs-compose",
]
gradle-plugins = [
    "gradle-plugin-agp",
    "gradle-plugin-compose",
    "gradle-plugin-compose-compiler",
    "gradle-plugin-serialization",
]
kotlinx = [
    "kotlinx-atomicfu",
    "kotlinx-datetime",
    "kotlinx-immutable",
    "kotlinx-serialization-json",
    "kotlinx-serialization-proto",
]
ktor-common = [
    "ktor-client-auth",
    "ktor-client-content-negotiation",
    "ktor-client-core",
    "ktor-client-encoding",
    "ktor-client-logging",
    "ktor-serialization-kotlinx-json",
]
