export const EditorConfig = {
  workflowFormatVersion: 1,
  defaultNodePosition: { x: 360, y: 160 },
  nodeWidth: 240,
  portVerticalOffset: 45,
  edgeControlOffset: 60,
  maximumEventCharacters: 6000,
  httpNotFound: 404,
  httpConflict: 409,
  defaultDeviceUrl: "http://localhost:8080",
  api: {
    manifest: "/api/v1/manifest",
    workflows: "/api/v1/workflows",
    validateWorkflow: "/api/v1/workflows/validate",
    events: "/api/v1/events",
    authorizationHeader: "Authorization",
    bearerPrefix: "Bearer ",
    eventAccessTokenQuery: "access_token",
  },
  eventType: {
    entryChanged: "editor.entry.changed",
    globalErrorChanged: "editor.global_error.changed",
    connectionRejected: "editor.connection.rejected",
    bridgeConnected: "bridge.connected",
    bridgeMessage: "bridge.message",
    bridgeError: "bridge.error",
    workflowSaved: "workflow.saved",
  },
};
